// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace poms_website_project_2._0.Migrations
{
    [DbContext(typeof(PomsDbContext))]
    [Migration("20250803144431_AssessmentFacultyLearnerUser")]
    partial class AssessmentFacultyLearnerUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("poms_website_project_2._0.Models.AdminDetailModel", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AdminDetailModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.AssessmentGradeModel", b =>
                {
                    b.Property<int>("AssessmentGradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentGradeId"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateGiven")
                        .HasColumnType("date");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int");

                    b.Property<int>("QuarterId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("AssessmentGradeId");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("LearnerId");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("SubjectId");

                    b.ToTable("AssessmentGradeModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.AssessmentModel", b =>
                {
                    b.Property<int>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssessmentId"));

                    b.Property<string>("AssessmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AssessmentNo")
                        .HasColumnType("int");

                    b.Property<string>("AssessmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateGiven")
                        .HasColumnType("date");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<int>("QuarterId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TotalItems")
                        .HasColumnType("int");

                    b.HasKey("AssessmentId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("SubjectId");

                    b.ToTable("AssessmentModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.AttendanceModel", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<int>("AttendanceStatus")
                        .HasColumnType("int");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("SchoolDate")
                        .HasColumnType("date");

                    b.HasKey("AttendanceId");

                    b.HasIndex("LearnerId");

                    b.ToTable("AttendanceModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.FacultyLoadModel", b =>
                {
                    b.Property<int>("LoadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoadId"));

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("LoadId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("SectionId");

                    b.HasIndex("SubjectId");

                    b.ToTable("FacultyLoadModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.FacultyModel", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("FacultyModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.GradeModel", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"));

                    b.Property<DateTime>("EncodedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("FinalGrade")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PtPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PtScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PtTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("QaPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("QaScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("QaTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WwPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WwScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WwTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("GradeId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("LearnerId");

                    b.HasIndex("SubjectId");

                    b.ToTable("GradeModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.LearnerModel", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<byte>("GradeLevel")
                        .HasColumnType("tinyint");

                    b.Property<string>("Lrn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("LearnerModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.NotificationModel", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.ParentLearnerModel", b =>
                {
                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int");

                    b.Property<string>("Relationship")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParentId");

                    b.HasIndex("LearnerId");

                    b.ToTable("ParentLearnerModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.ParentModel", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("ParentModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.QuarterModel", b =>
                {
                    b.Property<int>("QuarterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuarterId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<byte>("QuarterNo")
                        .HasColumnType("tinyint");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("QuarterId");

                    b.HasIndex("SchoolYearId");

                    b.ToTable("QuarterModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.RoleModel", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("RoleModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.SchoolFormModel", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormId"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneratedBy")
                        .HasColumnType("int");

                    b.Property<int>("GeneratedByNavigationUserId")
                        .HasColumnType("int");

                    b.Property<int>("LearnerId")
                        .HasColumnType("int");

                    b.HasKey("FormId");

                    b.HasIndex("GeneratedByNavigationUserId");

                    b.HasIndex("LearnerId");

                    b.ToTable("SchoolFormModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.SchoolYearModel", b =>
                {
                    b.Property<int>("SchoolYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolYearId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<short>("StartYear")
                        .HasColumnType("smallint");

                    b.HasKey("SchoolYearId");

                    b.ToTable("SchoolYearModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.SectionEnrolmentModel", b =>
                {
                    b.Property<int>("EnrolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrolId"));

                    b.Property<int>("LearnerId")
                        .HasColumnType("int");

                    b.Property<int>("SchoolYearId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("EnrolId");

                    b.HasIndex("LearnerId");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("SectionId");

                    b.ToTable("SectionEnrolmentModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.SectionModel", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SectionId"));

                    b.Property<byte>("GradeLevel")
                        .HasColumnType("tinyint");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SectionId");

                    b.ToTable("SectionModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.SubjectModel", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("SubjectCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SubjectId");

                    b.ToTable("SubjectModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserModel");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.AdminDetailModel", b =>
                {
                    b.HasOne("poms_website_project_2._0.Models.UserModel", "Admin")
                        .WithOne("AdminDetail")
                        .HasForeignKey("poms_website_project_2._0.Models.AdminDetailModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.AssessmentGradeModel", b =>
                {
                    b.HasOne("poms_website_project_2._0.Models.AssessmentModel", "Assessment")
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("poms_website_project_2._0.Models.FacultyModel", "Faculty")
                        .WithMany("AssessmentGrades")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("poms_website_project_2._0.Models.LearnerModel", "Learner")
                        .WithMany("AssessmentGrades")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("poms_website_project_2._0.Models.QuarterModel", "Quarter")
                        .WithMany("AssessmentGrades")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("poms_website_project_2._0.Models.SubjectModel", "Subject")
                        .WithMany("AssessmentGrades")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Faculty");

                    b.Navigation("Learner");

                    b.Navigation("Quarter");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.AssessmentModel", b =>
                {
                    b.HasOne("poms_website_project_2._0.Models.FacultyModel", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("poms_website_project_2._0.Models.QuarterModel", "Quarter")
                        .WithMany()
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("poms_website_project_2._0.Models.SubjectModel", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Quarter");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.AttendanceModel", b =>
                {
                    b.HasOne("poms_website_project_2._0.Models.LearnerModel", "Learner")
                        .WithMany("Attendances")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.FacultyLoadModel", b =>
                {
                    b.HasOne("poms_website_project_2._0.Models.FacultyModel", "Faculty")
                        .WithMany("FacultyLoads")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("poms_website_project_2._0.Models.SchoolYearModel", "SchoolYear")
                        .WithMany("FacultyLoads")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("poms_website_project_2._0.Models.SectionModel", "Section")
                        .WithMany("FacultyLoads")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("poms_website_project_2._0.Models.SubjectModel", "Subject")
                        .WithMany("FacultyLoads")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("SchoolYear");

                    b.Navigation("Section");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.FacultyModel", b =>
                {
                    b.HasOne("poms_website_project_2._0.Models.UserModel", "FacultyNavigation")
                        .WithOne("Faculty")
                        .HasForeignKey("poms_website_project_2._0.Models.FacultyModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacultyNavigation");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.GradeModel", b =>
                {
                    b.HasOne("poms_website_project_2._0.Models.FacultyModel", "Faculty")
                        .WithMany("Grades")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("poms_website_project_2._0.Models.LearnerModel", "Learner")
                        .WithMany("Grades")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("poms_website_project_2._0.Models.SubjectModel", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Learner");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.LearnerModel", b =>
                {
                    b.HasOne("poms_website_project_2._0.Models.UserModel", "LearnerNavigation")
                        .WithOne("Learner")
                        .HasForeignKey("poms_website_project_2._0.Models.LearnerModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearnerNavigation");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.NotificationModel", b =>
                {
                    b.HasOne("poms_website_project_2._0.Models.UserModel", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.ParentLearnerModel", b =>
                {
                    b.HasOne("poms_website_project_2._0.Models.LearnerModel", "Learner")
                        .WithMany("ParentLearners")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("poms_website_project_2._0.Models.ParentModel", "Parent")
                        .WithMany("ParentLearners")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.ParentModel", b =>
                {
                    b.HasOne("poms_website_project_2._0.Models.UserModel", "ParentNavigation")
                        .WithOne("Parent")
                        .HasForeignKey("poms_website_project_2._0.Models.ParentModel", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentNavigation");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.QuarterModel", b =>
                {
                    b.HasOne("poms_website_project_2._0.Models.SchoolYearModel", "SchoolYear")
                        .WithMany("Quarters")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.SchoolFormModel", b =>
                {
                    b.HasOne("poms_website_project_2._0.Models.UserModel", "GeneratedByNavigation")
                        .WithMany("SchoolForms")
                        .HasForeignKey("GeneratedByNavigationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("poms_website_project_2._0.Models.LearnerModel", "Learner")
                        .WithMany("SchoolForms")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneratedByNavigation");

                    b.Navigation("Learner");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.SectionEnrolmentModel", b =>
                {
                    b.HasOne("poms_website_project_2._0.Models.LearnerModel", "Learner")
                        .WithMany("SectionEnrolments")
                        .HasForeignKey("LearnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("poms_website_project_2._0.Models.SchoolYearModel", "SchoolYear")
                        .WithMany("SectionEnrolments")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("poms_website_project_2._0.Models.SectionModel", "Section")
                        .WithMany("SectionEnrolments")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Learner");

                    b.Navigation("SchoolYear");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.UserModel", b =>
                {
                    b.HasOne("poms_website_project_2._0.Models.RoleModel", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.FacultyModel", b =>
                {
                    b.Navigation("AssessmentGrades");

                    b.Navigation("FacultyLoads");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.LearnerModel", b =>
                {
                    b.Navigation("AssessmentGrades");

                    b.Navigation("Attendances");

                    b.Navigation("Grades");

                    b.Navigation("ParentLearners");

                    b.Navigation("SchoolForms");

                    b.Navigation("SectionEnrolments");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.ParentModel", b =>
                {
                    b.Navigation("ParentLearners");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.QuarterModel", b =>
                {
                    b.Navigation("AssessmentGrades");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.RoleModel", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.SchoolYearModel", b =>
                {
                    b.Navigation("FacultyLoads");

                    b.Navigation("Quarters");

                    b.Navigation("SectionEnrolments");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.SectionModel", b =>
                {
                    b.Navigation("FacultyLoads");

                    b.Navigation("SectionEnrolments");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.SubjectModel", b =>
                {
                    b.Navigation("AssessmentGrades");

                    b.Navigation("FacultyLoads");

                    b.Navigation("Grades");
                });

            modelBuilder.Entity("poms_website_project_2._0.Models.UserModel", b =>
                {
                    b.Navigation("AdminDetail");

                    b.Navigation("Faculty");

                    b.Navigation("Learner");

                    b.Navigation("Notifications");

                    b.Navigation("Parent");

                    b.Navigation("SchoolForms");
                });
#pragma warning restore 612, 618
        }
    }
}
